name: NFTX qt build - MacOS 11 Catalina


on:
  push:
    branches:
    - master
    - main
    - static


jobs:

  osx-build:
    name: OSX Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install deps (macOS)
        run: |
          brew update
          brew upgrade
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install gcc@8
          brew install gmp
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3
      - name: Build (macOS)
        run: |
          ./zcutil/build-mac.sh -j4
          mv src/qt/komodo-qt src/qt/NFTX-qt-osx
          zip --junk-paths NFTX-qt-mac src/qt/NFTX-qt-osx
      - name: Upload NFTX-qt-osx.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: NFTX-qt-osx
          path: ./NFTX-qt-osx.zip
